version: "3.4"
services:
  web:
    env_file: .env
    build:
      context: .
      target: build
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
